import { FC, PropsWithChildren } from 'react';

import Head from 'next/head'
import { Footer, Navbar } from '../ui';


interface Props extends PropsWithChildren {
    title: string;
    description: string;
}

export const BlogLayout: FC<Props> = ({ children, title, description }) => {
  return (
    <>
      <Head>
        <title>{ title }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main style={{
        margin: '80px auto',
        maxWidth: '1400px',
        padding: '0 30px',
        minHeight: '100vh'
      }}>
        { children }
      </main>

      <Footer />
    </>
  )
}

